#include "types.hpp"

#include <gtest/gtest.h>

TEST(Types_Color, InvertFlipsColor) { EXPECT_EQ(WHITE, ~BLACK); }

TEST(Types_Square, Arithmetic) {
    EXPECT_EQ(A1 + 1, B1);
    EXPECT_EQ(A1, B1 - 1);
    EXPECT_EQ(A1 + 8, A2);
    EXPECT_EQ(A1, A2 - 8);
}

TEST(Types_File, Arithmetic) {
    EXPECT_EQ(FILE1 + 1, FILE2);
    EXPECT_EQ(FILE1, FILE2 - 1);
}

TEST(Types_Rank, Arithmetic) {
    EXPECT_EQ(RANK1 + 1, RANK2);
    EXPECT_EQ(RANK1, RANK2 - 1);
}

TEST(Types_CastleRights, LogicOperators) {
    EXPECT_EQ(ALL_CASTLE & WHITE_CASTLE, WHITE_CASTLE);
    EXPECT_EQ(ALL_CASTLE ^ WHITE_CASTLE, BLACK_CASTLE);
    EXPECT_EQ(ALL_CASTLE ^ WHITE_OOO, BLACK_CASTLE | WHITE_OO);
    EXPECT_EQ(ALL_CASTLE ^ WHITE_OO, BLACK_CASTLE | WHITE_OOO);
    EXPECT_EQ(ALL_CASTLE & BLACK_CASTLE, BLACK_CASTLE);
    EXPECT_EQ(ALL_CASTLE ^ BLACK_CASTLE, WHITE_CASTLE);
    EXPECT_EQ(ALL_CASTLE ^ BLACK_OOO, WHITE_CASTLE | BLACK_OO);
    EXPECT_EQ(ALL_CASTLE ^ BLACK_OO, WHITE_CASTLE | BLACK_OOO);
}
